# Generated by Django 4.1.2 on 2022-10-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("dr", "Draft"), ("pu", "Pulblish")],
                default="dr",
                max_length=20,
            ),
        ),
    ]
