# Generated by Django 4.1.2 on 2022-10-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_post_date_post_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(upload_to="images"),
        ),
    ]
