# Generated by Django 4.1.2 on 2022-10-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_post_img"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="decription",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(),
        ),
    ]
