# Generated by Django 4.1.2 on 2022-10-09 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_post_decription_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="body",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="decription",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="img",
            field=models.ImageField(null=True, upload_to="images"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[("dr", "Draft"), ("pu", "Pulblish")],
                default="dr",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
