# Generated by Django 4.1.2 on 2022-10-09 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_post_body_alter_post_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(max_length=250, null=True),
        ),
    ]
