# Generated by Django 4.1.2 on 2022-10-09 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["date"]},
        ),
    ]
